create table Person(
    id int primary key generated by default as identity,
    username varchar(100) not null,
    year_of_birth int not null,
    password varchar not null
);

insert into person(username, year_of_birth, password)  values
    ('test_user_1', 1999, 'test_password'),
    ('test_user_2', 1999, 'test_password');
