create table person(
    id int primary key generated by default as identity,
    name varchar(100) not null,
    age int not null,
    email varchar not null
);

insert into person(name, age, email)  values
    ('test_user_1', 1999, 'email@email.xz'),
    ('test_user_2', 2000, 'test@email.xz');

alter table person add column role varchar(100) not null;